language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

env:
  - SLACK_VER_TOKEN='foo' TEAM_ID='123456' SLACK_API_TOKEN='bar'

before_install:
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
  - pip install coverage
  - pip install -r requirements.txt
install:
  - pip install .

script: pytest --cov=attaskcreator tests/

after_success:
  - codecov
