language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

before_install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
install:
  - pip install .
  - pip install -r requirements.txt
script: pytest --cov=attaskcreator tests/

after_sucess:
  - codecov
