language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

env:
  - SLACK_VER_TOKEN='foo'
  - TEAM_ID='123456'
  - SLACK_API_TOKEN='bar

before_install:
  - pip install pytest-cov
  - pip install pytest
  - pip install codecov
install:
  - pip install .
  - pip install -r requirements.txt
script: pytest --cov=attaskcreator/

after_sucess:
  - codecov
